import numpy as np
a1 = np.array [(1,2,3,4,5)]
print("a1",a1)
sum = np.sum(a1)
print("sum:",sum)
prod = np.prod(a1)
print("product",product)
mean=np.mean(a1)
print("mean",mean)
standard_deviation = np.std(a1)
print("standard_deviation", standard_deviation)
variance=np.var(a1)
print("variance",variance)
minimum = np.min(a1)
print("minimum value:",min)
maximum=np.max(a1)
print("maximum val:",maximum)
minimum_index=np.argmin(a1)
print("minimum_index:",minimum_index)
maximum_index=np.argmax(a1)
print("maximum_index:",maximum_index)
median=np.median(a1)
print("median:",median)

